version: "3.7"
services:
  # ganachecli: simulated test rpc on dev environment
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli
    ports:
      - 8545:8545
    networks:
      - my-proxy-net
networks:
  my-proxy-net:
    external:
      name: nft_network

