version: "3.7"
services:
  # ganachecli: simulated test rpc on dev environment
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli
    ports:
      - 8545:8545
  app:
    build: app/
    image: nft_service:latest
    container_name: nft_service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV="development"
      - SERVER_PORT="3000"

