version: '3.3'
services:
  app:
    build: .
    image: nft_service:latest
    container_name: nft_service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV="development"
      - SERVER_PORT="3000"
